apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: posts
  template:  # describes the templates by which the pods should be created
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: seagrendaniel/posts:latest
---
apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv
spec: 
  selector:
    app: posts
  type: ClusterIP # k8s defaults to this type if none is specified
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000