apiVersion: v1
kind: Service
metadata: 
  name: posts-srv
spec: 
  type: NodePort
  selector:
    app: posts  # find pods with a label of app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000 # port for Node Port Service
      targetPort: 4000 # port for actual pod that houses container w post image
      